Importing Torch and numpy and matplotlib
    

In [1]:
import torch
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

0.4.0


In [3]:
def activation(x):
    sig=1/(1+torch.exp(-x))
    return sig

In [4]:
torch.manual_seed(7);
features=torch.randn((1,5))
weights=torch.rand_like(features);
bias=torch.randn((1,1))

In [5]:
a=torch.mm(features,weights.view(5,1))+bias
output=activation(a);
print(output)

tensor([[ 0.6140]])


In [6]:
print(weights.shape)

torch.Size([1, 5])


In [9]:
torch.manual_seed(7)
features=torch.randn((1,3))
n_input=features.shape[1]
n_hidden=2
n_output=1

W1=torch.randn((n_input,n_hidden))
W2=torch.randn((n_hidden,n_output))

B1=torch.randn((1,n_hidden));
B2=torch.randn((1,n_output));

In [10]:
a1=activation(torch.mm(features,W1)+B1)
a2=activation(torch.mm(a1,W2)+B2)
print(a2)

tensor([[ 0.3171]])


In [11]:
a=np.random.rand(5,4)

In [12]:
a

array([[0.50283262, 0.82452354, 0.08361917, 0.13562569],
       [0.05897491, 0.01769853, 0.77213142, 0.05775496],
       [0.42173178, 0.41325548, 0.99153508, 0.12625122],
       [0.41626363, 0.76662015, 0.23525124, 0.48179001],
       [0.6138535 , 0.09795106, 0.81958122, 0.94935766]])

In [14]:
b=torch.from_numpy(a)

In [15]:
print(b)

tensor([[ 0.5028,  0.8245,  0.0836,  0.1356],
        [ 0.0590,  0.0177,  0.7721,  0.0578],
        [ 0.4217,  0.4133,  0.9915,  0.1263],
        [ 0.4163,  0.7666,  0.2353,  0.4818],
        [ 0.6139,  0.0980,  0.8196,  0.9494]], dtype=torch.float64)


In [16]:
print(b.numpy())

[[0.50283262 0.82452354 0.08361917 0.13562569]
 [0.05897491 0.01769853 0.77213142 0.05775496]
 [0.42173178 0.41325548 0.99153508 0.12625122]
 [0.41626363 0.76662015 0.23525124 0.48179001]
 [0.6138535  0.09795106 0.81958122 0.94935766]]


In [17]:
b.mul_(2)

tensor([[ 1.0057,  1.6490,  0.1672,  0.2713],
        [ 0.1179,  0.0354,  1.5443,  0.1155],
        [ 0.8435,  0.8265,  1.9831,  0.2525],
        [ 0.8325,  1.5332,  0.4705,  0.9636],
        [ 1.2277,  0.1959,  1.6392,  1.8987]], dtype=torch.float64)

In [18]:
a

array([[1.00566524, 1.64904708, 0.16723834, 0.27125138],
       [0.11794982, 0.03539707, 1.54426283, 0.11550992],
       [0.84346355, 0.82651097, 1.98307016, 0.25250243],
       [0.83252726, 1.5332403 , 0.47050248, 0.96358002],
       [1.227707  , 0.19590212, 1.63916243, 1.89871533]])

Above changes from memory